spring.application.name=project-tl-kr-BE

app.frontend.url=http://localhost:5173

#spring.datasource.url=jdbc:mysql://N5F9y2ABhkC86bx.root:y6dUTsnbEzxAoMI9@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
#spring.datasource.username=N5F9y2ABhkC86bx.root
#spring.datasource.password=y6dUTsnbEzxAoMI9

spring.datasource.url=jdbc:mysql://localhost:3306/project-tl-kr?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true